language: python
python:
- 2.6
- 2.7
- pypy
- 3.2
- 3.3
install:
- pip install . --use-mirrors
script: nosetests
notifications:
  email:
    recipients:
    - travisci@aweber.com
deploy:
  provider: pypi
  user: aweber
  password:
    secure: ZA9hYIJA7AZwCeytO04OiJA5UQ6Ktbjg1ImFhSCXaF2y6wMtVedummF4lWMvDLlpmcFv7/TNQPyQMreLeXUoP+A7N1tZSywi9dZTONsBpdWjhyf1YR/NYP611g7/fXctSCVL4rrU/5Kq6AskjRG199+ZXcmlFRL3HLyY4hCCeS0=
  on:
    tags: true
    repo: aweber/srvlookup
    all_branches: true
    python: 2.7
