language: python
python:
- 2.6
- 2.7
- pypy
- 3.2
- 3.3
install:
- pip install . --use-mirrors
script: nosetests
notifications:
  email:
    recipients:
    - travisci@aweber.com
deploy:
  provider: pypi
  user: sprockets
  password:
    secure: BrBleAN0R/Hqflp7JmaOFp8O33rCfS6f/xqYPrxLR2yuNltWKIpQ1K6y+uZQV3l8f/4Jpvlil4RuWeXiLbUwpD7LeduUnBozGMiKLy3nymB6/Gm14+Bmt6DcR+gWLwJQBaTfSg+XyQMK0Js6+VCxSE+OfKWDhmUDLBlJunIyHmE=
  on:
    tags: true
    repo: aweber/srvlookup
    all_branches: true
    python: 2.7
