sudo: false
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install .
  - pip install wheel
script: nosetests
deploy:
  provider: pypi
  user: crad
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: gmr/srvlookup
    all_branches: true
    python: 2.7
  password:
    secure: "Hc6EfDEI0gbQ8XSxitEaCXBGaQPhW7f4NoWxBUDgIhJBp+VuYmT8XYX8TWco7Tq3gXSFSzq/mjK5XkouKwjmcymzO23AOyY+sZ8uV18vLXjUCbgY+vJbGs+7QLp3mtrUyp4ePebIgNosC4HyiamX67fHtLpBcDYP3MOhgx36+j8="
