language: python
python:
- 2.6
- 2.7
- pypy
- 3.2
- 3.3
install:
- pip install . --use-mirrors
script: nosetests
notifications:
  email:
    recipients:
    - travisci@aweber.com
deploy:
  provider: pypi
  user: aweber
  password:
    secure: DhyiG/Nb3cWTymnlCxE0938C0Ke0er8CLsljLm3UUupVrXKCgf6qKVqe77KPWSlVMWQB7jAnKakAITYLnLbbr5vIU/ak12m310UTuKSzZE+o9Mi4oOknOqXj1ROZGOGdCMkMaAn5Wxo4qzrQshGb+1dADvecPtSgywHRGlRtTpQ=
  on:
    tags: true
    repo: aweber/srvlookup
    all_branches: true
    python: 2.7
